### ISSUE TITLE
404 Invalid HOST

### ISSUE THREAD

**Issue by CodeMongerrr** [CodeMongerrr/Certicryp#1]
While using the fetch function in the app(UniversitySignUp) I am not able to fetch the API 

![image](https://github.com/CodeMongerrr/Certicryp/assets/99281767/25e49ac6-2560-43f5-aee9-8c018436397a)

**Comment by IbrahimG88** [comment]
Hi CodeMongerr, I would like to help. This is my first contribution :). I have had a look at your code. To test this fetch request it we need the server-side code that include the folder api that has the file createusers to be able to further test signing up users. Currently te request is sent to a file that is not available. Correct me if I am missing something.

**Comment by CodeMongerrr** [comment]
Understood my mistake! Thanks for helping me out

**Comment by IbrahimG88** [comment]
Hello Aditya, you are welcome. Let me know if you need further help. Best
of Luck!

Ibrahim
